# These are supported funding model platforms

github: [bartholomej] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: bartholomej
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: ['https://www.paypal.me/bartholomej']
