name: Build & Tests & Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: 📦 Enable Corepack
        run: corepack enable

      - name: 🔧 Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Sync versions
        run: yarn syncprojects

      - name: Build ngx-scrolltop
        run: yarn build

      - name: Build Schematics
        run: yarn build:schematics

      - name: Build demo app
        run: yarn build:demo --base-href https://bartholomej.github.io/ngx-scrolltop/

      - name: Run tests
        run: yarn test

      - name: Publish NPM
        run: cd dist/ngx-scrolltop && npm publish --provenance --access public

      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist/demo/browser
