name: Build & run all tests

on: [push]

jobs:
  test:
    environment: develop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: 📦 Enable Corepack
        run: corepack enable

      - name: 🔧 Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies # Install all deps
        run: yarn install --immutable

      - name: Sync versions # Sync versions
        run: yarn syncprojects

      - name: Build ngx-scrolltop # Build
        run: yarn build

      - name: Build Schematics # Build Schematics and move
        run: yarn build:schematics

      - name: Build demo # Build demo page
        run: yarn build:demo

      - name: Run tests # Build Schematics and move
        run: yarn test --configuration=ci
